permalink:           pretty

# Setup
title:               'introduction to Deep Learning (Undergrad)'
url:                 https://atcold.github.io/NYU-DLFL25U/
baseurl:             '/NYU-DLFL25U'
homepage_title:      Home
default_lang:        'en'

# About/contact
author:
name:                atcold
url:                 https://twitter.com/alfcnz
github:
  repo:              https://github.com/atcold/NYU-DLFL25U

# Custom vars
version:             dlfl25u

src:                 "."
default_theme:       "ayu"

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# For Maths
markdown:            kramdown

# To use hljs, disable the default highlighter
kramdown:
  syntax_highlighter_opts:
    disable: true
  math_engine: null

exclude:
  - jekyllbook
  - vendor


################################### English ####################################
# prologues:
#   - path: en/faq.md
chapters:
  - path: projects/template/report.md
  - path: projects/rnn_memory_capacity/report.md